In [1]:
# Back propagation Neural Network


#        Inputs                     Output
#    0     0    1                      0
#    1     1    1                      1
#    1     0    1                      1
#    0     1    1                      0

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# sigmoid function

def nlinear(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))


In [5]:
# input dataset


X=np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

# output dataset

y=np.array([[0,0,1,1]]).T

# seed random numbers for random distributions

np.random.seed(1)

synapse0=2*np.random.random((3,1))-1
synapsecopy=synapse0

In [6]:
for i in range(1000):
    
    # forward propagation
    
    layer0=X
    layer1=nlinear(np.dot(layer0,synapse0))
    
    #calculate
    
    layer1_error=y-layer1
    
    #multiplying how much error backpropagated
    # slope of the sigmoid at the values in layer 1
    
    layer1_delta= layer1_error*nlinear(layer1,True)
    
    # update weights as per the errors backpropagates
    synapse0+=np.dot(layer0.T,layer1_delta)


In [7]:
print("Output:")
print(layer1)
print("Actual Output")
print(y)

Output:
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]
Actual Output
[[0]
 [0]
 [1]
 [1]]


In [8]:
layer0

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [13]:
synapse0

array([[ 7.26283009],
       [-0.21614618],
       [-3.41703015]])

In [19]:
Q,R=np.linalg.qr(synapsecopy)
print("\nQ=", Q, "\n\nR=", R)


Q= [[-0.90452786]
 [ 0.02691929]
 [ 0.42556399]] 

R= [[-8.02941562]]


In [20]:
decompose=Q*R
decompose

array([[ 7.26283009],
       [-0.21614618],
       [-3.41703015]])

In [21]:
layer1=nlinear(np.dot(layer0,decompose))
layer1

array([[0.03176745],
       [0.02575143],
       [0.97907779],
       [0.97416005]])